name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  connect-sql-server:
    runs-on: windows-latest
    env:
      SQL_SERVER_DATA: ""
      SQL_USER: ""
      SQL_PASSWORD: ""
      SQL_DATABASE: ""
      PATH_RELEASE_APP: ""

    steps:
      - name: ⚙️ Checkout code
        uses: actions/checkout@v2

      - name: 📄 Load configuration from JSON
        shell: pwsh
        id: load_config
        run: |
          # read JSON file
          $config = Get-Content -Raw -Path "config.json" | ConvertFrom-Json
          
          # Check JSON file
          Write-Output "Config Loaded: $($config | ConvertTo-Json -Depth 3)"

          $SQL_SERVER_DATA = $config.SQL_SERVER_DATA
          $SQL_USER = $config.SQL_USER
          $SQL_PASSWORD = $config.SQL_PASSWORD
          $SQL_DATABASE = $config.SQL_DATABASE
          $PATH_RELEASE_APP = $config.PATH_RELEASE_APP

          # Assign JSON values to environment variables
          Add-Content -Path $env:GITHUB_ENV -Value "SQL_SERVER_DATA=$SQL_SERVER_DATA"
          Add-Content -Path $env:GITHUB_ENV -Value "SQL_USER=$SQL_USER"
          Add-Content -Path $env:GITHUB_ENV -Value "SQL_PASSWORD=$SQL_PASSWORD"
          Add-Content -Path $env:GITHUB_ENV -Value "SQL_DATABASE=$SQL_DATABASE"
          Add-Content -Path $env:GITHUB_ENV -Value "PATH_RELEASE_APP=$PATH_RELEASE_APP"

      - name: 📝 Verify environment variables
        shell: pwsh
        run: |
          Write-Output "SQL_SERVER_DATA: $env:SQL_SERVER_DATA"
          Write-Output "SQL_USER: $env:SQL_USER"
          Write-Output "SQL_PASSWORD: $env:SQL_PASSWORD"
          Write-Output "SQL_DATABASE: $env:SQL_DATABASE"
          Write-Output "PATH_RELEASE_APP: $env:PATH_RELEASE_APP"

      - name: 📦 Unzip the release package
        shell: pwsh
        run: |
            # Ensure the .zip file exists and then unzip it
            $zipFile = "$env:PATH_RELEASE_APP"
            $unzipFolder = "$env:PATH_RELEASE_APP\extracted"
        
            # Debugging: Output the final zip file path
            Write-Output "Checking for ZIP file at: $zipFile"
        
            # Check if the zip file exists
            if (Test-Path -Path $zipFile) {
                Write-Output "Unzipping file $zipFile"
                
                # Create a temporary folder to unzip to
                if (-Not (Test-Path -Path $unzipFolder)) {
                    Write-Output "Creating extraction folder at: $unzipFolder"
                    New-Item -ItemType Directory -Path $unzipFolder
                }
        
                # Initialize the progress bar
                $totalFiles = (Get-Content $zipFile | Measure-Object -Line).Lines  # Approximate number of files
                $progress = 0
        
                # Extract the zip file and simulate progress
                Expand-Archive -Path $zipFile -DestinationPath $unzipFolder -Force
        
                # Simulate progress bar for unzip operation
                $files = Get-ChildItem -Path $unzipFolder -Recurse
                $filesCount = $files.Count
                $progressStep = [math]::Ceiling($filesCount / 100)
                
                for ($i = 1; $i -le $filesCount; $i++) {
                    if ($i % $progressStep -eq 0) {
                        $progress = [math]::Round(($i / $filesCount) * 100)
                        Write-Progress -PercentComplete $progress -Status "Unzipping..." -Activity "$i of $filesCount files extracted"
                    }
                }
        
                Write-Output "Unzipped to $unzipFolder"
            } else {
                Write-Error "Zip file not found at $zipFile"
                exit 1
            }
        
      - name: 🛠️ Install SQL Server tools
        run: choco install sqlcmd
           
      - name: 🏃‍♂️‍➡️ Execute SQL Scripts in Order
        shell: pwsh
        run: |     
            $folders = Get-ChildItem -Path $env:PATH_RELEASE_APP\extracted -Recurse -Directory | Sort-Object FullName
            
            foreach ($folder in $folders) {
              if ($folder.Name -notmatch '^\d') {
                Write-Output "Skipping folder (no number in name): $($folder.FullName)"
                continue
              }
              Write-Output "Processing folder: $($folder.FullName)"
              $sqlFiles = Get-ChildItem -Path $folder.FullName -Filter *.sql | Sort-Object Name
            
              foreach ($file in $sqlFiles) {            
                try {
                  Write-Output "Executing $($file.FullName)..."
                  $output = sqlcmd -S $env:SQL_SERVER_DATA -U $env:SQL_USER -P $env:SQL_PASSWORD -d $env:SQL_DATABASE -i $file.FullName 2>&1
                  Write-Output "Result of $($file.Name):"
                  if ($output -match 'Msg \d+, Level \d+, State \d+, Server .+, Line \d+') {
                    Write-Output "❗Error executing $($file.Name): $output"
                  } 
                  else {
                    Write-Output "✅ Successfully executed $($file.Name)"
                  }
                } catch {
                  Write-Error "❌ Failed to execute $($file.Name): $($_.Exception.Message)"
                }
              }
            }
