# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  connect-sql-server:
    runs-on: windows-latest # Use the latest windows runner

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up .NET SDK (only needed if the project involves .NET tools)
    - name: Set up .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0' # Specify the .NET version

    # Step 3: Install SQL Server tools (sqlcmd)
    - name: Set up .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0'

    # Step 4: Connect to the SQL Server and run a query
    - name: Connect to SQL Server and run a query
      env:
        SQL_SERVER: 'mes-arido-database.database.windows.net'  
        SQL_USER: 'opdbmanager'   
        SQL_PASSWORD: 'DBM4n4g3r'  
        SQL_DATABASE: 'MESDB'  # Replace with the name of your database
      run: |
        # Use sqlcmd to connect to the SQL Server and execute a query
        sqlcmd -S $SQL_SERVER -U $SQL_USER -P $SQL_PASSWORD -d $SQL_DATABASE -Q "SELECT * FROM Sites FOR JSON AUTO;" -o result.json
        
        # Check if the result.json file was created successfully
        if (Test-Path ./result.json) {
          Write-Host "The result.json file was created successfully."
        } else {
          Write-Host "The result.json file could not be created."
          exit 1 # Exit the script with an error code if the file is not created
        }

    - name: Display JSON Output
      if: success() # Execute this step only if the previous steps succeeded
      run: |
        # Display the content of the JSON file
        type ./result.json
