name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  connect-sql-server:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SQL Server tools
        run: choco install sqlcmd

      - name: List directory contents
        run: |
          # List the files in the working directory to check if the script exists
          Get-ChildItem -Recurse

      - name: Execute Specific SQL Script
        shell: pwsh
        env:
          SQL_SERVER: ${{ secrets.SQL_SERVER }}
          SQL_USER: ${{ secrets.SQL_USER }}
          SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
          SQL_DATABASE: ${{ secrets.SQL_DATABASE }}
        run: |
          $scriptPath = "220 - SQL/03 - AppVersion.sql"
          Write-Output "Executing script: ${scriptPath}"

          # Check if the file exists
          if (-Not (Test-Path $scriptPath)) {
            Write-Error "Script not found: $scriptPath"
            exit 1
          }

          try {
            # Execute the specific SQL script
            $output = sqlcmd -S $env:SQL_SERVER -U $env:SQL_USER -P $env:SQL_PASSWORD -d $env:SQL_DATABASE -i $scriptPath 2>&1

            # Print the output for visibility
            Write-Output "Result of ${scriptPath}:"
            Write-Output $output

            # Check for errors in the output
            if ($LASTEXITCODE -ne 0) {
              Write-Error "Error executing script: $output"
            } else {
              Write-Output "Successfully executed the script."
            }
          } catch {
            Write-Error "Failed to execute the script: $($_.Exception.Message)"
          }
