name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  connect-sql-server:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SQL Server tools
        run: choco install sql-server-management-studio

      - name: Execute SQL Scripts
        env:
          SQL_SERVER: ${{ secrets.SQL_SERVER }}
          SQL_USER: ${{ secrets.SQL_USER }}
          SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
          SQL_DATABASE: ${{ secrets.SQL_DATABASE }}
        run: |
          $sqlFiles = Get-ChildItem -Path "./220 - SQL" -Filter *.sql -Recurse
          foreach ($file in $sqlFiles) {
            try {
              Invoke-Sqlcmd -ServerInstance $env:SQL_SERVER -Database $env:SQL_DATABASE -Username $env:SQL_USER -Password $env:SQL_PASSWORD -InputFile $file.FullName
              Write-Output "Successfully executed $($file.FullName)"
            } catch {
              Write-Error "Failed to execute $($file.FullName): $($_.Exception.Message)"
            }
          }
