name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  connect-sql-server:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SQL Server tools
        run: choco install sql-server-management-studio

      - name: Connect to SQL Server
        env:
          SQL_SERVER: ${{ secrets.SQL_SERVER }}
          SQL_USER: ${{ secrets.SQL_USER }}
          SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
          SQL_DATABASE: ${{ secrets.SQL_DATABASE }}
        run: |
          Invoke-Sqlcmd -ServerInstance $env:SQL_SERVER -Database $env:SQL_DATABASE -Username $env:SQL_USER -Password $env:SQL_PASSWORD -Query "SELECT * FROM Sites FOR JSON AUTO;" -o result.json

      # Step 4: Display JSON Output
      - name: Display JSON Output
        if: success()
        run: |
          # Display the content of the JSON file
          type result.json
          